name: macos-direct-vncstupid

on:
  workflow_dispatch:

jobs:
  macos-job:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ngrok
        run: |
          brew install ngrok/ngrok/ngrok
          NGROK_PATH=$(which ngrok)
          $NGROK_PATH config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: VNC Hazirligi (Sifreli ve Guvenli)
        run: |
          # VNC'yi kur ve sifreyi bas (Cunku VNC Viewer sifresiz baglantiyi sevmez)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvncpw -vncpw Ed0kaleen!2024 -restart -agent -privs -all
          
      - name: Ngrok TCP Tunelini Atesle
        run: |
          NGROK_PATH=$(which ngrok)
          # Bu sefer HTTP degil, direkt TCP 5900 portunu aciyoruz
          nohup $NGROK_PATH tcp 5900 --log=stdout > /dev/null &
          sleep 20
          # Baglanti adresini aliyoruz
          curl -s http://localhost:4040/api/tunnels | python3 -c "import sys, json; print('\n--- VNC VIEWER ADRESI ---\n' + json.load(sys.stdin)['tunnels'][0]['public_url'].replace('tcp://', '') + '\n-----------------------')"

      - name: Stay Online
        run: |
          start_time=$(date +%s)
          while [ $(($(date +%s) - start_time)) -lt 255600 ]; do
            echo "Sequoia TCP Nobetinde... $(date)"
            sleep 300
          done
          
